# Generated by Django 3.2.8 on 2021-10-30 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import epc.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='ComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='defaults/component_group_default.png', upload_to=epc.models.component_group_directory_path)),
            ],
            options={
                'verbose_name': 'Component Group',
                'verbose_name_plural': 'Component Groups',
                'db_table': 'component_group',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'db_table': 'generation',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=634)),
                ('part_code', models.CharField(max_length=64)),
                ('sales_restriction', models.PositiveSmallIntegerField(choices=[(0, 'Over-the-Counter(No VIN)'), (1, 'Tesla Only'), (2, 'Restricted'), (3, 'E-Procurement'), (4, 'Not for Resale'), (5, 'Unrestricted(VIN)')], default=0)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('order_quantity', models.PositiveSmallIntegerField()),
                ('availability', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('is_original', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Part',
                'verbose_name_plural': 'Parts',
                'db_table': 'part',
            },
        ),
        migrations.CreateModel(
            name='PartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=84)),
                ('picture', models.ImageField(default='defaults/part_group_default.png', upload_to=epc.models.part_group_directory_path)),
            ],
            options={
                'verbose_name': 'Part Group',
                'verbose_name_plural': 'Part Groups',
                'db_table': 'part_group',
            },
        ),
        migrations.CreateModel(
            name='RestorePasswordSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_slice', models.CharField(max_length=16)),
                ('time_of_request', models.IntegerField(default=1635608772)),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'restore_password_session',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.brand')),
            ],
            options={
                'verbose_name': 'Model',
                'verbose_name_plural': 'Models',
                'db_table': 'model',
            },
        ),
        migrations.CreateModel(
            name='M2MPartGroupToPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('info', models.CharField(max_length=200)),
                ('repair_quantity', models.PositiveSmallIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.brand')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.component')),
                ('component_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.componentgroup')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.part')),
                ('part_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.partgroup')),
            ],
            options={
                'verbose_name': '(M2M) Part Group to Part',
                'verbose_name_plural': '(M2M) Part Groups to Parts',
                'db_table': 'm2m_part_group_to_part',
            },
        ),
        migrations.AddField(
            model_name='generation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.componentgroup'),
        ),
    ]
