# Generated by Django 3.2.8 on 2021-10-30 16:48

from django.db import migrations, models
import django.db.models.deletion
import epc.models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentgroup',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='partgroup',
            name='picture',
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1635612488),
        ),
        migrations.CreateModel(
            name='PicPartGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='defaults/part_group_default.png', upload_to=epc.models.pic_part_group_directory_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.brand')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model')),
                ('part_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.partgroup')),
            ],
        ),
        migrations.CreateModel(
            name='PicComponentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(default='defaults/component_group_default.png', upload_to=epc.models.pic_component_group_directory_path)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.brand')),
                ('component_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.componentgroup')),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model')),
            ],
        ),
    ]
