# Generated by Django 3.2.8 on 2021-10-30 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0002_auto_20211030_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piccomponentgroup',
            options={'verbose_name': 'Picture (Component Group)', 'verbose_name_plural': 'Pictures (Component Group)'},
        ),
        migrations.AlterModelOptions(
            name='picpartgroup',
            options={'verbose_name': 'Picture (Part Group)', 'verbose_name_plural': 'Pictures (Part Group)'},
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1635612859),
        ),
        migrations.AlterModelTable(
            name='piccomponentgroup',
            table='pic_component_group',
        ),
        migrations.AlterModelTable(
            name='picpartgroup',
            table='pic_part_group',
        ),
    ]
