# Generated by Django 3.2.8 on 2021-10-31 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0003_auto_20211030_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1635639344),
        ),
    ]
