# Generated by Django 3.2.8 on 2021-10-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0005_auto_20211031_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='partgroup',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epc.component'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1635691907),
        ),
    ]
