# Generated by Django 3.2.8 on 2021-11-23 21:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0006_auto_20211031_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='code',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='generation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model', chained_model_field='model', on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='piccomponentgroup',
            name='generation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model', chained_model_field='model', on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='piccomponentgroup',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='picpartgroup',
            name='generation',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='model', chained_model_field='model', on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='picpartgroup',
            name='model',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='brand', chained_model_field='brand', on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1637701504),
        ),
    ]
