# Generated by Django 3.2.8 on 2021-11-23 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0007_auto_20211123_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='code',
        ),
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='piccomponentgroup',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='piccomponentgroup',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='picpartgroup',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.generation'),
        ),
        migrations.AlterField(
            model_name='picpartgroup',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epc.model'),
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1637702696),
        ),
    ]
