# Generated by Django 3.2.8 on 2021-12-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0008_auto_20211123_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1638965378),
        ),
    ]
