# Generated by Django 3.2.8 on 2021-12-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0009_alter_restorepasswordsessions_time_of_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1638965542),
        ),
    ]
