# Generated by Django 3.2.8 on 2021-12-16 23:58

from django.db import migrations, models
import epc.models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0011_auto_20211209_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picpartgroup',
            name='picture',
            field=models.FileField(default='defaults/part_group_default.png', max_length=500, upload_to=epc.models.pic_part_group_directory_path),
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1639699111),
        ),
    ]
