# Generated by Django 3.2.8 on 2021-12-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0013_auto_20211227_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m2mpartgrouptopart',
            name='info',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1640606555),
        ),
    ]
