# Generated by Django 3.2.8 on 2022-01-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0018_alter_restorepasswordsessions_time_of_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1642420589),
        ),
    ]
