# Generated by Django 3.2.8 on 2022-02-10 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0019_alter_restorepasswordsessions_time_of_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partgroup',
            name='component',
        ),
        migrations.AddField(
            model_name='picpartgroup',
            name='component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epc.component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picpartgroup',
            name='component_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='epc.componentgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restorepasswordsessions',
            name='time_of_request',
            field=models.IntegerField(default=1644451248),
        ),
    ]
